# Configuration file
# key = value
snello.dbtype=postgresql
snello.documenttype=fs

quarkus.datasource.mysql.db-kind=mysql
quarkus.datasource.mysql.username=snello
quarkus.datasource.mysql.password=snello
quarkus.datasource.mysql.jdbc.url=jdbc:mysql://localhost:3306/snello
quarkus.datasource.mysql.jdbc.min-size=1
quarkus.datasource.mysql.jdbc.max-size=5
quarkus.datasource.mysql.jdbc=true


quarkus.datasource.postgresql.db-kind=postgresql
quarkus.datasource.postgresql.username=snello
quarkus.datasource.postgresql.password=snello
quarkus.datasource.postgresql.jdbc.url=jdbc:postgresql://localhost:5432/snello
quarkus.datasource.postgresql.jdbc.min-size=1
quarkus.datasource.postgresql.jdbc.max-size=5
quarkus.datasource.postgresql.jdbc=true

quarkus.datasource.h2.db-kind=h2
quarkus.datasource.h2.username=snello
quarkus.datasource.h2.password=snello
quarkus.datasource.h2.jdbc.url=jdbc:postgresql://localhost:5432/snello
quarkus.datasource.h2.jdbc.min-size=1
quarkus.datasource.h2.jdbc.max-size=5
quarkus.datasource.h2.jdbc=true
