# Configuration file
# key = value
snello.dbtype=postgresql
snello.documenttype=fs

quarkus.datasource.mysql.db-kind=mysql
quarkus.datasource.mysql.username=snello
quarkus.datasource.mysql.password=snello
quarkus.datasource.mysql.jdbc.url=jdbc:mysql://localhost:3306/snello
quarkus.datasource.mysql.jdbc.min-size=1
quarkus.datasource.mysql.jdbc.max-size=5
quarkus.datasource.mysql.jdbc=true


quarkus.datasource.postgresql.db-kind=postgresql
quarkus.datasource.postgresql.username=snello
quarkus.datasource.postgresql.password=snello
quarkus.datasource.postgresql.jdbc.url=jdbc:postgresql://localhost:5432/snello
quarkus.datasource.postgresql.jdbc.min-size=1
quarkus.datasource.postgresql.jdbc.max-size=5
quarkus.datasource.postgresql.jdbc=true

quarkus.datasource.h2.db-kind=h2
quarkus.datasource.h2.username=sa
quarkus.datasource.h2.password=
quarkus.datasource.h2.jdbc.url=jdbc:h2:file:../src/main/resources/data/database;AUTO_SERVER=true;DB_CLOSE_DELAY=-1
quarkus.datasource.h2.jdbc.min-size=1
quarkus.datasource.h2.jdbc.max-size=5
quarkus.datasource.h2.jdbc=true


# storage
snello.storagetype=s3


# queries
snello.dbtype=mysql
snello.h2.queries.select-users=select 1
snello.h2.queries.select-classes=select * from classes

snello.mysql.queries.select-users=select 1
snello.mysql.queries.select-classes=select * from classes

snello.postgresql.queries.select-users=select 1
snello.postgresql.queries.select-classes=select * from classes


# OIDC
quarkus.ssl.native=true
quarkus.smallrye-jwt.enabled=false
quarkus.oidc.enabled=false
quarkus.oidc.auth-server-url=https://sso.n-ess.it/auth/realms/lab
#to replace with it's corresponding keycloak client
quarkus.oidc.client-id=lab
